default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  host: localhost
  database: gorails_dev

test:
  <<: *default
  database: gorails_test

production:
  <<: *default
  database: gorails_prod
  username: postgres
  password: <%= ENV['BANNER_DATABASE_PASSWORD'] %>