# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af89b6a76cc02816d25a2340dc31d2a8cb751e9e63b0ace3ad9de2951367d8c1bf160b96f2df43182ee879f4173f940f88402e294842b9afa3273cb381f53c4d

test:
  secret_key_base: 6c71bdba0cbe96dbb15ba354e1cfad90e3847f5b9c9e5d45f4dcedd0fc860008e05485252f2c893bd47d0bd29dc6aa830f39f91f35c313e08f7900a5dd2fd5ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
